version: '3'  # specify docker-compose version
services:
  backend:
    build: ./backend
    container_name: django-backend
    ports:
      - 8000:8000
    networks:
      - project-network
  frontend:
    build: .
    container_name: nextjs-frontend
    ports:
      - 3000:3000
    depends_on:
      - django-backend
    networks:
      - project-network
networks:
  project-network:
