version: '3.8'  # specify docker-compose version
services:
  frontend:
    build: .
    container_name: nextjs-frontend
    # restart: always
    ports:
      - 3000:3000
    depends_on:
      - backend
    # networks:
    #   - mynetwork
  backend:
    build: ./backend
    container_name: django-backend
    # restart: always
    ports:
      - 8000:8000
    # networks:
    #   - mynetwork

# networks:
#   mynetwork: