# Generated by Django 4.0.3 on 2022-04-29 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_category_description_category_svg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='svg',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
