# Generated by Django 4.0.3 on 2022-04-29 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_category_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='svg',
            new_name='url',
        ),
    ]
