# Generated by Django 4.0.3 on 2022-06-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='full_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
